Repository SecretHouseGame/ngx-design-system, pull requests merged in 2022-06, with the labels that each got.

#100 feat: add checkboxes & radio style
  projects/ngx-ds-secret-house/assets/scss/_inputs.scss
  projects/ngx-ds-secret-house/assets/styles.scss
  projects/ngx-ds-secret-house/ng-package.json
  projects/ngx-ds-secret-house/src/lib/components/buttons/button/button.component.ts
  projects/ngx-ds-secret-house/src/lib/components/form/field-container/field-container.component.scss
  projects/ngx-ds-secret-house/src/lib/components/form/input-checkbox/input-checkbox.component.html
  projects/ngx-ds-secret-house/src/lib/components/form/input-checkbox/input-checkbox.component.scss
  projects/ngx-ds-secret-house/src/lib/components/form/input-checkbox/input-checkbox.component.ts
  projects/ngx-ds-secret-house/src/lib/components/form/input-radio/input-radio.component.html
  projects/ngx-ds-secret-house/src/lib/components/form/input-radio/input-radio.component.scss
  projects/ngx-ds-secret-house/src/lib/components/interfaces/checkbox-option.ts
  projects/ngx-ds-secret-house/src/lib/components/interfaces/radio-option.ts
  projects/ngx-ds-secret-house/src/public-api.ts
  stories/form/InputCheckbox.stories.ts
  stories/form/InputRadio.stories.ts
Labels: Ready

#105 feat: active animation in switch and add style
  projects/ngx-ds-secret-house/src/lib/components/form/input-switch/input-switch.component.html
  projects/ngx-ds-secret-house/src/lib/components/form/input-switch/input-switch.component.scss
  projects/ngx-ds-secret-house/src/lib/components/form/input-switch/input-switch.component.ts
  stories/form/InputSwitch.stories.ts
Labels: Ready

#108 ci: fix ci to deploy npm
  .github/workflows/deploy-storybook.yml
Labels: Ready

#91 feat: add button-action in storybook
  package-lock.json
  stories/buttons/Button-action.stories.ts
  yarn.lock
Labels: OpenSource

#95 feat (AvatarComponent/StoryBook): add AvatarIcon Component
  projects/ngx-ds-secret-house/src/lib/components/utils/avatar/avatar.component.html
  projects/ngx-ds-secret-house/src/lib/components/utils/avatar/avatar.component.scss
  projects/ngx-ds-secret-house/src/lib/components/utils/avatar/avatar.component.spec.ts
  projects/ngx-ds-secret-house/src/lib/components/utils/avatar/avatar.component.ts
  projects/ngx-ds-secret-house/src/lib/ngx-ds-secret-house.module.ts
  stories/utils/Avatar.stories.ts
  yarn.lock
Labels: OpenSource

#113 chore(main): release 1.1.1
  projects/ngx-ds-secret-house/CHANGELOG.md
  projects/ngx-ds-secret-house/package.json
Labels: autorelease: pending

#115 chore(main): release 1.1.2
  projects/ngx-ds-secret-house/CHANGELOG.md
  projects/ngx-ds-secret-house/package.json
Labels: autorelease: pending

#121 chore(main): release 1.1.3
  projects/ngx-ds-secret-house/CHANGELOG.md
  projects/ngx-ds-secret-house/package.json
Labels: autorelease: pending
